MFGSLUG = "generic"
SLUG = "patch-panel-12p-st"
MODEL = "Patch Panel 12 Ports ST"
U_HEIGHT = "1"
IS_FULL_DEPTH = False

R_F_PORT = "Port 1/2"
R_F_PORT_TYPE = "2000"

# Rear Port 1/2
#NEW_REAR_PORT_TEMPLATE = RearPortTemplate()
#NEW_REAR_PORT_TEMPLATE.device_type_id = NEW_DEVICE_TYPE.id
#NEW_REAR_PORT_TEMPLATE.name = "Port 1/2"
#NEW_REAR_PORT_TEMPLATE.type = "2000"
#NEW_REAR_PORT_TEMPLATE.positions = "1"
#NEW_REAR_PORT_TEMPLATE.save()

# Front Port 1/2
#NEW_FRONT_PORT_TEMPLATE = FrontPortTemplate()
#NEW_FRONT_PORT_TEMPLATE.device_type_id = NEW_DEVICE_TYPE.id
#NEW_FRONT_PORT_TEMPLATE.name = "Port 1/2"
#NEW_FRONT_PORT_TEMPLATE.rear_port_id = NEW_REAR_PORT_TEMPLATE.id
#NEW_FRONT_PORT_TEMPLATE.type = "2000"
#NEW_FRONT_PORT_TEMPLATE.rear_port_position = "1"
#NEW_FRONT_PORT_TEMPLATE.save()

# Rear Port 3/4
NEW_REAR_PORT_TEMPLATE = RearPortTemplate()
NEW_REAR_PORT_TEMPLATE.device_type_id = NEW_DEVICE_TYPE.id
NEW_REAR_PORT_TEMPLATE.name = "Port 3/4"
NEW_REAR_PORT_TEMPLATE.type = "2000"
NEW_REAR_PORT_TEMPLATE.positions = "1"
NEW_REAR_PORT_TEMPLATE.save()

# Front Port 3/4
NEW_FRONT_PORT_TEMPLATE = FrontPortTemplate()
NEW_FRONT_PORT_TEMPLATE.device_type_id = NEW_DEVICE_TYPE.id
NEW_FRONT_PORT_TEMPLATE.name = "Port 3/4"
NEW_FRONT_PORT_TEMPLATE.rear_port_id = NEW_REAR_PORT_TEMPLATE.id
NEW_FRONT_PORT_TEMPLATE.type = "2000"
NEW_FRONT_PORT_TEMPLATE.rear_port_position = "1"
NEW_FRONT_PORT_TEMPLATE.save()

# Rear Port 5/6
NEW_REAR_PORT_TEMPLATE = RearPortTemplate()
NEW_REAR_PORT_TEMPLATE.device_type_id = NEW_DEVICE_TYPE.id
NEW_REAR_PORT_TEMPLATE.name = "Port 5/6"
NEW_REAR_PORT_TEMPLATE.type = "2000"
NEW_REAR_PORT_TEMPLATE.positions = "1"
NEW_REAR_PORT_TEMPLATE.save()

# Front Port 5/6
NEW_FRONT_PORT_TEMPLATE = FrontPortTemplate()
NEW_FRONT_PORT_TEMPLATE.device_type_id = NEW_DEVICE_TYPE.id
NEW_FRONT_PORT_TEMPLATE.name = "Port 5/6"
NEW_FRONT_PORT_TEMPLATE.rear_port_id = NEW_REAR_PORT_TEMPLATE.id
NEW_FRONT_PORT_TEMPLATE.type = "2000"
NEW_FRONT_PORT_TEMPLATE.rear_port_position = "1"
NEW_FRONT_PORT_TEMPLATE.save()

# Rear Port 7/8
NEW_REAR_PORT_TEMPLATE = RearPortTemplate()
NEW_REAR_PORT_TEMPLATE.device_type_id = NEW_DEVICE_TYPE.id
NEW_REAR_PORT_TEMPLATE.name = "Port 7/8"
NEW_REAR_PORT_TEMPLATE.type = "2000"
NEW_REAR_PORT_TEMPLATE.positions = "1"
NEW_REAR_PORT_TEMPLATE.save()

# Front Port 7/8
NEW_FRONT_PORT_TEMPLATE = FrontPortTemplate()
NEW_FRONT_PORT_TEMPLATE.device_type_id = NEW_DEVICE_TYPE.id
NEW_FRONT_PORT_TEMPLATE.name = "Port 7/8"
NEW_FRONT_PORT_TEMPLATE.rear_port_id = NEW_REAR_PORT_TEMPLATE.id
NEW_FRONT_PORT_TEMPLATE.type = "2000"
NEW_FRONT_PORT_TEMPLATE.rear_port_position = "1"
NEW_FRONT_PORT_TEMPLATE.save()

# Rear Port 9/10
NEW_REAR_PORT_TEMPLATE = RearPortTemplate()
NEW_REAR_PORT_TEMPLATE.device_type_id = NEW_DEVICE_TYPE.id
NEW_REAR_PORT_TEMPLATE.name = "Port 9/10"
NEW_REAR_PORT_TEMPLATE.type = "2000"
NEW_REAR_PORT_TEMPLATE.positions = "1"
NEW_REAR_PORT_TEMPLATE.save()

# Front Port 9/10
NEW_FRONT_PORT_TEMPLATE = FrontPortTemplate()
NEW_FRONT_PORT_TEMPLATE.device_type_id = NEW_DEVICE_TYPE.id
NEW_FRONT_PORT_TEMPLATE.name = "Port 9/10"
NEW_FRONT_PORT_TEMPLATE.rear_port_id = NEW_REAR_PORT_TEMPLATE.id
NEW_FRONT_PORT_TEMPLATE.type = "2000"
NEW_FRONT_PORT_TEMPLATE.rear_port_position = "1"
NEW_FRONT_PORT_TEMPLATE.save()

# Rear Port 11/12
NEW_REAR_PORT_TEMPLATE = RearPortTemplate()
NEW_REAR_PORT_TEMPLATE.device_type_id = NEW_DEVICE_TYPE.id
NEW_REAR_PORT_TEMPLATE.name = "Port 11/12"
NEW_REAR_PORT_TEMPLATE.type = "2000"
NEW_REAR_PORT_TEMPLATE.positions = "1"
NEW_REAR_PORT_TEMPLATE.save()

# Front Port 11/12
NEW_FRONT_PORT_TEMPLATE = FrontPortTemplate()
NEW_FRONT_PORT_TEMPLATE.device_type_id = NEW_DEVICE_TYPE.id
NEW_FRONT_PORT_TEMPLATE.name = "Port 11/12"
NEW_FRONT_PORT_TEMPLATE.rear_port_id = NEW_REAR_PORT_TEMPLATE.id
NEW_FRONT_PORT_TEMPLATE.type = "2000"
NEW_FRONT_PORT_TEMPLATE.rear_port_position = "1"
NEW_FRONT_PORT_TEMPLATE.save()
