MFGSLUG = "hpe"
SLUG = "storefabric-sn3600b-32gb-24-24-fibre-channel"
MODEL = "StoreFabric SN3600B 32Gb 24/24 Fibre Channel Switch"
U_HEIGHT = "1"
PART_NUMBER = 'Q1H71B'
IS_FULL_DEPTH = True

POWER_PORT = "PS1"
POWER_PORT = "PS2"

IFACE_FF = '1000'
OOB_MGMT = 'MGMT'

IFACE_FF = '3320'
INTERFACE = 'Port 0'
INTERFACE = 'Port 1'
INTERFACE = 'Port 2'
INTERFACE = 'Port 3'
INTERFACE = 'Port 4'
INTERFACE = 'Port 5'
INTERFACE = 'Port 6'
INTERFACE = 'Port 7'
INTERFACE = 'Port 8'
INTERFACE = 'Port 9'
INTERFACE = 'Port 10'
INTERFACE = 'Port 11'
INTERFACE = 'Port 12'
INTERFACE = 'Port 13'
INTERFACE = 'Port 14'
INTERFACE = 'Port 15'
INTERFACE = 'Port 16'
INTERFACE = 'Port 17'
INTERFACE = 'Port 18'
INTERFACE = 'Port 19'
INTERFACE = 'Port 20'
INTERFACE = 'Port 21'
INTERFACE = 'Port 22'
INTERFACE = 'Port 23'