MFGSLUG = "sophos"
SLUG = "sg310-rev-1"
MODEL = "SG310 Rev.1"
U_HEIGHT = "1"
IS_FULL_DEPTH = True

POWER_PORT = "PS1"

IFACE_FF = '1000'
INTERFACE = 'E0/LAN'
INTERFACE = 'E1/WAN'
INTERFACE = 'E2/DMZ'
INTERFACE = 'E3/HA'
INTERFACE = 'E4'
INTERFACE = 'E5'
INTERFACE = 'E6'
INTERFACE = 'E7'

IFACE_FF = '1100'
INTERFACE = 'E8'
INTERFACE = 'E9'

