MFGSLUG = "apc"
SLUG = "smart-ups-srt-3000-va"
MODEL = "Smart-UPS SRT 3000 VA"
PART_NUMBER = "SRT3000RMXLI"
U_HEIGHT = "2"
IS_FULL_DEPTH = True

POWER_OUTLET = "GRP1_1_C19"
POWER_OUTLET = "GRP1_2_C13"
POWER_OUTLET = "GRP1_3_C13"
POWER_OUTLET = "GRP1_4_C13"
POWER_OUTLET = "GRP1_5_C13"
POWER_OUTLET = "GRP2_1_C19"
POWER_OUTLET = "GRP2_2_C13"
POWER_OUTLET = "GRP2_3_C13"
POWER_OUTLET = "GRP2_4_C13"
POWER_OUTLET = "GRP2_5_C13"

POWER_PORT = "IEC-320_C20"

NEW_INTERFACE_TEMPLATE = InterfaceTemplate.objects.get(device_type_id=NEW_DEVICE_TYPE.id, name="Network")
NEW_INTERFACE_TEMPLATE.form_factor="100"
NEW_INTERFACE_TEMPLATE.mgmt_only=True
NEW_INTERFACE_TEMPLATE.save()
