MFGSLUG = "apc"
SLUG = "smart-ups-srt-1500-va"
MODEL = "Smart-UPS SRT 1500 VA"
PART_NUMBER = "SRT1500RMXLI"
U_HEIGHT = "2"
IS_FULL_DEPTH = True

POWER_OUTLET = "GRP1_1_C13"
POWER_OUTLET = "GRP1_2_C13"
POWER_OUTLET = "GRP1_3_C13"
POWER_OUTLET = "GRP2_1_C13"
POWER_OUTLET = "GRP2_2_C13"
POWER_OUTLET = "GRP2_3_C13"

POWER_PORT = "IEC-320_C14"

NEW_INTERFACE_TEMPLATE = InterfaceTemplate.objects.get(device_type_id=NEW_DEVICE_TYPE.id, name="Network")
NEW_INTERFACE_TEMPLATE.form_factor="100"
NEW_INTERFACE_TEMPLATE.mgmt_only=True
NEW_INTERFACE_TEMPLATE.save()
