MFGSLUG = "apc"
SLUG = "smart-ups-srt-5000-va"
MODEL = "Smart-UPS SRT 5000 VA"
PART_NUMBER = "SRT5KRMXLI"
U_HEIGHT = "3"
IS_FULL_DEPTH = True

POWER_OUTLET = "GRP1_L1"
POWER_OUTLET = "GRP1_L2"
POWER_OUTLET = "GRP1_L3"
POWER_OUTLET = "GRP1_R1"
POWER_OUTLET = "GRP1_R2"
POWER_OUTLET = "GRP1_R3"
POWER_OUTLET = "GRP2_L1"
POWER_OUTLET = "GRP2_L2"
POWER_OUTLET = "GRP2_R1"
POWER_OUTLET = "GRP2_R2"

NEW_INTERFACE_TEMPLATE = InterfaceTemplate.objects.get(device_type_id=NEW_DEVICE_TYPE.id, name="Network")
NEW_INTERFACE_TEMPLATE.form_factor="100"
NEW_INTERFACE_TEMPLATE.mgmt_only=True
NEW_INTERFACE_TEMPLATE.save()
